import configparser

# CONFIG
config = configparser.ConfigParser()
config.read('dwh.cfg')
IAM_ROLE = config['IAM_ROLE']['ARN']
PMT_DATA = config['S3']['PMT_DATA']
RSH_DATA = config['S3']['RSH_DATA']
PHY_DATA = config['S3']['PHY_DATA']

# DROP TABLES

staging_physicians_table_drop = "DROP TABLE IF EXISTS staging_physicians"
staging_payments_table_drop = "DROP TABLE IF EXISTS staging_payments"
staging_research_table_drop = "DROP TABLE IF EXISTS staging_research"

# CREATE TABLES

staging_physicians_table_create = ("""
        CREATE TABLE IF NOT EXISTS staging_physicians (
        Change_Type                                                         VARCHAR(20),
        Physician_Profile_ID                                                NUMERIC(38,0),
        Physician_First_Name                                                VARCHAR(20),
        Physician_Middle_Name                                               VARCHAR(20),
        Physician_Last_Name                                                 VARCHAR(35),
        Physician_Name_Suffix                                               VARCHAR(5),
        Recipient_Primary_Business_Street_Address_Line1                     VARCHAR(55),
        Recipient_Primary_Business_Street_Address_Line2                     VARCHAR(55),
        Recipient_City                                                      VARCHAR(40),
        Recipient_State                                                     CHAR(2),
        Recipient_Zip_Code                                                  VARCHAR(10),
        Recipient_Country                                                   VARCHAR(100),
        Recipient_Province                                                  VARCHAR(20),
        Recipient_Postal_Code                                               VARCHAR(20),
        Physician_Primary_Type                                              VARCHAR(50),
        Physician_Specialty                                                 VARCHAR(300),
        Record_ID                                                           NUMERIC(38,0),
        Program_Year                                                        CHAR(4),
        Total_Amount_Invested_USDollars                                     NUMERIC(12,2),
        Value_of_Interest                                                   NUMERIC(12,2),
        Terms_of_Interest                                                   VARCHAR(500),
        Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name           VARCHAR(100),
        Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID         NUMERIC(38,0),
        Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name       VARCHAR(100),
        Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State      CHAR(2),
        Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country    VARCHAR(100),
        Dispute_Status_for_Publication                                      CHAR(3),
        Interest_Held_by_Physician_or_an_Immediate_Family_Member            VARCHAR(50),
        Payment_Publication_Date                                            DATE)
        """)

staging_payments_table_create = ("""
        CREATE TABLE IF NOT EXISTS staging_payments (
        Change_Type                                                         VARCHAR(20),
        Covered_Recipient_Type                                              VARCHAR(50),
        Teaching_Hospital_CCN                                               VARCHAR(6),
        Teaching_Hospital_ID                                                NUMERIC(38,0),
        Teaching_Hospital_Name                                              VARCHAR(100),
        Physician_Profile_ID                                                NUMERIC(38,0),
        Physician_First_Name                                                VARCHAR(20),
        Physician_Middle_Name                                               VARCHAR(20),
        Physician_Last_Name                                                 VARCHAR(35),
        Physician_Name_Suffix                                               VARCHAR(5),
        Recipient_Primary_Business_Street_Address_Line1                     VARCHAR(55),
        Recipient_Primary_Business_Street_Address_Line2                     VARCHAR(55),
        Recipient_City                                                      VARCHAR(40),
        Recipient_State                                                     CHAR(2),
        Recipient_Zip_Code                                                  VARCHAR(10),
        Recipient_Country                                                   VARCHAR(100),
        Recipient_Province                                                  VARCHAR(20),
        Recipient_Postal_Code                                               VARCHAR(20),
        Primary_Physician_Type                                              VARCHAR(100),
        Physician_Specialty                                                 VARCHAR(300),
        Physician_License_State_code1                                       CHAR(2),
        Physician_License_State_code2                                       CHAR(2),
        Physician_License_State_code3                                       CHAR(2),
        Physician_License_State_code4                                       CHAR(2),
        Physician_License_State_code5                                       CHAR(2),
        Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name           VARCHAR(100),
        Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID         VARCHAR(12),
        Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name       VARCHAR(100),
        Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State      CHAR(2),
        Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country    VARCHAR(100),
        Total_Amount_of_Payment_USDollars                                   NUMERIC(12,2),
        Date_of_Payment                                                     DATE,
        Number_of_Payments_Included_in_Total_Amount                         NUMERIC(3,0),
        Form_of_Payment_or_Transfer_of_Value                                VARCHAR(100),
        Nature_of_Payment_or_Transfer_of_Value                              VARCHAR(200),
        City_of_Travel                                                      VARCHAR(40),
        State_of_Travel                                                     CHAR(2),
        Country_of_Travel                                                   VARCHAR(100),
        Physician_Ownership_Indicator                                       CHAR(3),
        Third_Party_Payment_Recipient_Indicator                             VARCHAR(50),
        Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value   VARCHAR(50),
        Charity_Indicator                                                   CHAR(3),
        Third_Party_Equals_Covered_Recipient_Indicator                      CHAR(3),
        Contextual_Information                                              VARCHAR(500),
        Delay_in_Publication_Indicator                                      CHAR(3),
        Record_ID                                                           NUMERIC(38,0),
        Dispute_Status_for_Publication                                      CHAR(3),
        Related_Product_Indicator                                           VARCHAR(100),
        Covered_or_Noncovered_Indicator_1                                   VARCHAR(100),
        Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1           VARCHAR(100),
        Product_Category_or_Therapeutic_Area_1                              VARCHAR(100),
        Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1            VARCHAR(500),
        Associated_Drug_or_Biological_NDC_1                                 VARCHAR(100),
        Covered_or_Noncovered_Indicator_2                                   VARCHAR(100),
        Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2           VARCHAR(100),
        Product_Category_or_Therapeutic_Area_2                              VARCHAR(100),
        Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2            VARCHAR(500),
        Associated_Drug_or_Biological_NDC_2                                 VARCHAR(100),
        Covered_or_Noncovered_Indicator_3                                   VARCHAR(100),
        Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3           VARCHAR(100),
        Product_Category_or_Therapeutic_Area_3                              VARCHAR(100),
        Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3            VARCHAR(500),
        Associated_Drug_or_Biological_NDC_3                                 VARCHAR(100),
        Covered_or_Noncovered_Indicator_4                                   VARCHAR(100),
        Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4           VARCHAR(100),
        Product_Category_or_Therapeutic_Area_4                              VARCHAR(100),
        Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4            VARCHAR(500),
        Associated_Drug_or_Biological_NDC_4                                 VARCHAR(100),
        Covered_or_Noncovered_Indicator_5                                   VARCHAR(100),
        Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5           VARCHAR(100),
        Product_Category_or_Therapeutic_Area_5                              VARCHAR(100),
        Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5            VARCHAR(500),
        Associated_Drug_or_Biological_NDC_5                                 VARCHAR(100),
        Program_Year                                                        CHAR(4),
        Payment_Publication_Date                                            DATE)
        """)

staging_research_table_create = ("""
        CREATE TABLE IF NOT EXISTS staging_research (
        Change_Type                                                         VARCHAR(20),
        Covered_Recipient_Type                                              VARCHAR(50),
        Noncovered_Recipient_Entity_Name                                    VARCHAR(50),
        Teaching_Hospital_CCN                                               VARCHAR(6),
        Teaching_Hospital_ID                                                NUMERIC(38,0),
        Teaching_Hospital_Name                                              VARCHAR(100),
        Physician_Profile_ID                                                NUMERIC(38,0),
        Physician_First_Name                                                VARCHAR(20),
        Physician_Middle_Name                                               VARCHAR(20),
        Physician_Last_Name                                                 VARCHAR(35),
        Physician_Name_Suffix                                               VARCHAR(5),
        Recipient_Primary_Business_Address_Line1                            VARCHAR(55),
        Recipient_Primary_Business_Address_Line2                            VARCHAR(55),
        Recipient_City                                                      VARCHAR(40),
        Recipient_State                                                     CHAR(2),
        Recipient_Zip_Code                                                  VARCHAR(10),
        Recipient_Country                                                   VARCHAR(100),
        Recipient_Province                                                  VARCHAR(20),
        Recipient_Postal_Code                                               VARCHAR(20),
        Physician_Primary_Type                                              VARCHAR(50),
        Physician_Specialty                                                 VARCHAR(300),
        Physician_License_State_code1                                       CHAR(2),
        Physician_License_State_code2                                       CHAR(2),
        Physician_License_State_code3                                       CHAR(2),
        Physician_License_State_code4                                       CHAR(2),
        Physician_License_State_code5                                       CHAR(2),
        Principal_Investigator_1_Profile_ID                                 NUMERIC(38,0),
        Principal_Investigator_1_First_Name                                 VARCHAR(20),
        Principal_Investigator_1_Middle_Name                                VARCHAR(20),
        Principal_Investigator_1_Last_Name                                  VARCHAR(35),
        Principal_Investigator_1_Name_Suffix                                VARCHAR(5),
        Principal_Investigator_1_Business_Street_Address_Line1              VARCHAR(55),
        Principal_Investigator_1_Business_Street_Address_Line2              VARCHAR(55),
        Principal_Investigator_1_City                                       VARCHAR(40),
        Principal_Investigator_1_State                                      CHAR(2),
        Principal_Investigator_1_Zip_Code                                   VARCHAR(10),
        Principal_Investigator_1_Country                                    VARCHAR(100),
        Principal_Investigator_1_Province                                   VARCHAR(20),
        Principal_Investigator_1_Postal_Code                                VARCHAR(20),
        Principal_Investigator_1_Primary_Type                               VARCHAR(50),
        Principal_Investigator_1_Specialty                                  VARCHAR(300),
        Principal_Investigator_1_License_State_code1                        CHAR(2),
        Principal_Investigator_1_License_State_code2                        CHAR(2),
        Principal_Investigator_1_License_State_code3                        CHAR(2),
        Principal_Investigator_1_License_State_code4                        CHAR(2),
        Principal_Investigator_1_License_State_code5                        CHAR(2),
        Principal_Investigator_2_Profile_ID                                 NUMERIC(38,0),
        Principal_Investigator_2_First_Name                                 VARCHAR(20),
        Principal_Investigator_2_Middle_Name                                VARCHAR(20),
        Principal_Investigator_2_Last_Name                                  VARCHAR(35),
        Principal_Investigator_2_Name_Suffix                                VARCHAR(5),
        Principal_Investigator_2_Business_Street_Address_Line1              VARCHAR(55),
        Principal_Investigator_2_Business_Street_Address_Line2              VARCHAR(55),
        Principal_Investigator_2_City                                       VARCHAR(40),
        Principal_Investigator_2_State                                      CHAR(2),
        Principal_Investigator_2_Zip_Code                                   VARCHAR(10),
        Principal_Investigator_2_Country                                    VARCHAR(100),
        Principal_Investigator_2_Province                                   VARCHAR(20),
        Principal_Investigator_2_Postal_Code                                VARCHAR(20),
        Principal_Investigator_2_Primary_Type                               VARCHAR(50),
        Principal_Investigator_2_Specialty                                  VARCHAR(300),
        Principal_Investigator_2_License_State_code1                        CHAR(2),
        Principal_Investigator_2_License_State_code2                        CHAR(2),
        Principal_Investigator_2_License_State_code3                        CHAR(2),
        Principal_Investigator_2_License_State_code4                        CHAR(2),
        Principal_Investigator_2_License_State_code5                        CHAR(2),
        Principal_Investigator_3_Profile_ID                                 NUMERIC(38,0),
        Principal_Investigator_3_First_Name                                 VARCHAR(20),
        Principal_Investigator_3_Middle_Name                                VARCHAR(20),
        Principal_Investigator_3_Last_Name                                  VARCHAR(35),
        Principal_Investigator_3_Name_Suffix                                VARCHAR(5),
        Principal_Investigator_3_Business_Street_Address_Line1              VARCHAR(55),
        Principal_Investigator_3_Business_Street_Address_Line2              VARCHAR(55),
        Principal_Investigator_3_City                                       VARCHAR(40),
        Principal_Investigator_3_State                                      CHAR(2),
        Principal_Investigator_3_Zip_Code                                   VARCHAR(10),
        Principal_Investigator_3_Country                                    VARCHAR(100),
        Principal_Investigator_3_Province                                   VARCHAR(20),
        Principal_Investigator_3_Postal_Code                                VARCHAR(20),
        Principal_Investigator_3_Primary_Type                               VARCHAR(50),
        Principal_Investigator_3_Specialty                                  VARCHAR(300),
        Principal_Investigator_3_License_State_code1                        CHAR(2),
        Principal_Investigator_3_License_State_code2                        CHAR(2),
        Principal_Investigator_3_License_State_code3                        CHAR(2),
        Principal_Investigator_3_License_State_code4                        CHAR(2),
        Principal_Investigator_3_License_State_code5                        CHAR(2),
        Principal_Investigator_4_Profile_ID                                 NUMERIC(38,0),
        Principal_Investigator_4_First_Name                                 VARCHAR(20),
        Principal_Investigator_4_Middle_Name                                VARCHAR(20),
        Principal_Investigator_4_Last_Name                                  VARCHAR(35),
        Principal_Investigator_4_Name_Suffix                                VARCHAR(5),
        Principal_Investigator_4_Business_Street_Address_Line1              VARCHAR(55),
        Principal_Investigator_4_Business_Street_Address_Line2              VARCHAR(55),
        Principal_Investigator_4_City                                       VARCHAR(40),
        Principal_Investigator_4_State                                      CHAR(2),
        Principal_Investigator_4_Zip_Code                                   VARCHAR(10),
        Principal_Investigator_4_Country                                    VARCHAR(100),
        Principal_Investigator_4_Province                                   VARCHAR(20),
        Principal_Investigator_4_Postal_Code                                VARCHAR(20),
        Principal_Investigator_4_Primary_Type                               VARCHAR(50),
        Principal_Investigator_4_Specialty                                  VARCHAR(300),
        Principal_Investigator_4_License_State_code1                        CHAR(2),
        Principal_Investigator_4_License_State_code2                        CHAR(2),
        Principal_Investigator_4_License_State_code3                        CHAR(2),
        Principal_Investigator_4_License_State_code4                        CHAR(2),
        Principal_Investigator_4_License_State_code5                        CHAR(2),
        Principal_Investigator_5_Profile_ID                                 NUMERIC(38,0),
        Principal_Investigator_5_First_Name                                 VARCHAR(20),
        Principal_Investigator_5_Middle_Name                                VARCHAR(20),
        Principal_Investigator_5_Last_Name                                  VARCHAR(35),
        Principal_Investigator_5_Name_Suffix                                VARCHAR(5),
        Principal_Investigator_5_Business_Street_Address_Line1              VARCHAR(55),
        Principal_Investigator_5_Business_Street_Address_Line2              VARCHAR(55),
        Principal_Investigator_5_City                                       VARCHAR(40),
        Principal_Investigator_5_State                                      CHAR(2),
        Principal_Investigator_5_Zip_Code                                   VARCHAR(10),
        Principal_Investigator_5_Country                                    VARCHAR(100),
        Principal_Investigator_5_Province                                   VARCHAR(20),
        Principal_Investigator_5_Postal_Code                                VARCHAR(20),
        Principal_Investigator_5_Primary_Type                               VARCHAR(50),
        Principal_Investigator_5_Specialty                                  VARCHAR(300),
        Principal_Investigator_5_License_State_code1                        CHAR(2),
        Principal_Investigator_5_License_State_code2                        CHAR(2),
        Principal_Investigator_5_License_State_code3                        CHAR(2),
        Principal_Investigator_5_License_State_code4                        CHAR(2),
        Principal_Investigator_5_License_State_code5                        CHAR(2),
        Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name           VARCHAR(100),
        Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID         NUMERIC(38,0),
        Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name       VARCHAR(100),
        Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State      CHAR(2),
        Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country    VARCHAR(100),
        Related_Product_Indicator                                           VARCHAR(100),
        Covered_or_Noncovered_Indicator_1                                   VARCHAR(100),
        Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1           VARCHAR(100),
        Product_Category_or_Therapeutic_Area_1                              VARCHAR(100),
        Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1            VARCHAR(500),
        Associated_Drug_or_Biological_NDC_1                                 VARCHAR(100),
        Covered_or_Noncovered_Indicator_2                                   VARCHAR(100),
        Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2           VARCHAR(100),
        Product_Category_or_Therapeutic_Area_2                              VARCHAR(100),
        Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2            VARCHAR(500),
        Associated_Drug_or_Biological_NDC_2                                 VARCHAR(100),
        Covered_or_Noncovered_Indicator_3                                   VARCHAR(100),
        Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3           VARCHAR(100),
        Product_Category_or_Therapeutic_Area_3                              VARCHAR(100),
        Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3            VARCHAR(500),
        Associated_Drug_or_Biological_NDC_3                                 VARCHAR(100),
        Covered_or_Noncovered_Indicator_4                                   VARCHAR(100),
        Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4           VARCHAR(100),
        Product_Category_or_Therapeutic_Area_4                              VARCHAR(100),
        Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4            VARCHAR(500),
        Associated_Drug_or_Biological_NDC_4                                 VARCHAR(100),
        Covered_or_Noncovered_Indicator_5                                   VARCHAR(100),
        Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5           VARCHAR(100),
        Product_Category_or_Therapeutic_Area_5                              VARCHAR(100),
        Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5            VARCHAR(500),
        Associated_Drug_or_Biological_NDC_5                                 VARCHAR(100),
        Total_Amount_of_Payment_USDollars                                   NUMERIC(12,2),
        Date_of_Payment                                                     DATE,
        Form_of_Payment_or_Transfer_of_Value                                VARCHAR(100),
        Expenditure_Category1                                               VARCHAR(50),
        Expenditure_Category2                                               VARCHAR(50),
        Expenditure_Category3                                               VARCHAR(50),
        Expenditure_Category4                                               VARCHAR(50),
        Expenditure_Category5                                               VARCHAR(50),
        Expenditure_Category6                                               VARCHAR(50),
        Preclinical_Research_Indicator                                      CHAR(3),
        Delay_in_Publication_Indicator                                      CHAR(3),
        Name_of_Study                                                       VARCHAR(500),
        Dispute_Status_for_Publication                                      CHAR(3),
        Record_ID                                                           NUMERIC(38,0),
        Program_Year                                                        CHAR(4),
        Payment_Publication_Date                                            DATE,
        ClinicalTrials_Gov_Identifier                                       VARCHAR(11),
        Research_Information_Link                                           VARCHAR(2083),
        Context_of_Research                                                 VARCHAR(500))
        """)


# QUERY LISTS

create_staging_table_queries = [staging_physicians_table_create, staging_payments_table_create, staging_research_table_create]
drop_staging_table_queries = [staging_physicians_table_drop, staging_payments_table_drop, staging_research_table_drop]
